The name of the province was derived from the Malay word "Samba" meaning to worship as the inhabitants were found by the Spaniards to be worshhipping spirits called "Anitos". The inhabitants where then referred to as "Sambali" or the hispanized "Zambals". Zambales is a province located in the Central Luzon region,being second to the largest among the 7 provinces of the region with a land area of 3,830.83 sq. kilometers.<br/>
The province is abundant in natural resources, the fruit Mango being the most popular of them all, plentiful during the months of January to April. Clearly, nature's generosity did not stop there; Zambales has a lot of unpolluted islands and coves as well as well-preserved landscapes and forests. The town of Pundaquit has 8 magnificent destinations that can only be accessed by boat or by trekking namely,<br/>
<b>Agnaem Cove</b> - The nearest cove from Pundaquit Beach, it was once a private cove but was later on opened up to the public.<br/>
<b>Talisayen Cove</b> - A privately owned cove but locals and tourists are welcome to visit. The cove also has an access to a Grotto, where a magnificent view of the ocean can be seen.<br/>
<b>Anawangin Cove</b> - Considered the most popular cove in Pundaquit, teeming with pine trees, camping sites, and a lake smack in the middle of the cove.<br/>
<b>Nagsasa Cove</b> - A wider cove and less crowded, that has ample room for campers and tourists for a day tour or overnight stay.<br/>
<b>Silanguin Cove</b> - This cove is the farthest from the rest of the coves with over an hour travel time by boat. It is also considered the largest, secluded, and less inhabited<br/>
Some coves can be accessed by foot, but in order to schedule a trek to these magnificent coves, the local government of the province will require you to register at the Barangay and have a local guide to walk you through.<br/>
The islands on the other hand can only be accessed by boat, but are equally as amazing and as resplendent as locals claim.<br/>
<b>Camara Island</b> - One of the nearest islands in Pundaquit and very popular for rock climbers with its unique rock formations.<br/>
<b>Capones Island</b> - A stone's throw away from Camara Island, Capones has access to the well-known Spanish Lighthouse, a great location for relaxation and picnics.<br/>
<b>Magalawa Island</b> - This is the farthest island located off the coast of Palauig, the stretch of powder white sand beach is perfect for campers and the preserve coral reefs and marine life makes it the best location for snorkeling.<br/>
<b>Potipot Island</b> - The island of Potipot is located in the town of Candelaria popular for its crystal blue waters and white fine sand. There are cottages available for rent that makes it a perfect place romantic getaways and barkada trips.<br/>
Casa San Miguel Foundation is also in the Pundaquit area, a 15 hectare mango orchard that has sheltered and educated generations of talented individuals. Living to their aim to "integrate culture and community development" in Zambales. They offer accommodation and a cafe where quite a few local delicacies that are definitely world class. For a more laid back travels, head your way to the town of San Narciso where Crystal Beach Resort can be found. A popular beach resort in town where surfing is the main event, every year the Summer Siren Festival is also celebrated annually.<br/>
Zambales is quiet a location, rich in produce, teeming beaches, and hospitable locals, maybe a little undiscovered but definitely worth the travel.